---
name: Receptor Testing

'on':
  - push
  - pull_request

jobs:
  build:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install receptor and its dev/test dependencies
        run: |
          poetry install
      - name: Perform integration tests
        run: |
          poetry run pytest ./test/perf/ -s

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dateutil pytest pytest-asyncio
          pip install .
      - name: pytest unit tests
        run: |
          pytest test/integration test/unit

  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run flake8
        run: poetry run flake8

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Lint yaml files
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: true
