name: Receptor Perf Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dateutil
        pip install .
        pip install -r scripts/requirements.txt
    - name: Perform perf test
      run: |
        python ./scripts/node_utils.py file scripts/topology.yaml&
        sleep 10
        python scripts/node_utils.py ping scripts/topology.yaml --count 100 --validate 0.1
