---
- name: Deploy Receptor Mesh Network
  hosts: all
  vars:
    # could be "1.0", etc.
    receptor_version: git+https://github.com/project-receptor/receptor
  roles:
    - role: receptor_install
      become: true
